/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecretaryRouteImport } from './routes/secretary'
import { Route as PractitionerRouteImport } from './routes/practitioner'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DisplayRouteImport } from './routes/display'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SecretaryIndexRouteImport } from './routes/secretary/index'
import { Route as PractitionerIndexRouteImport } from './routes/practitioner/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SecretaryPaiementsRouteImport } from './routes/secretary/paiements'
import { Route as SecretaryAgendaRouteImport } from './routes/secretary/agenda'
import { Route as PractitionerSelectBoxRouteImport } from './routes/practitioner/select-box'
import { Route as PractitionerActiveRouteImport } from './routes/practitioner/active'
import { Route as AdminQueueRouteImport } from './routes/admin/queue'
import { Route as AdminPaiementsRouteImport } from './routes/admin/paiements'
import { Route as AdminAgendaRouteImport } from './routes/admin/agenda'
import { Route as SecretaryPreConsultationsIndexRouteImport } from './routes/secretary/pre-consultations/index'
import { Route as SecretaryPatientsIndexRouteImport } from './routes/secretary/patients/index'
import { Route as AdminPreConsultationsIndexRouteImport } from './routes/admin/pre-consultations/index'
import { Route as AdminPatientsIndexRouteImport } from './routes/admin/patients/index'
import { Route as SecretaryPreConsultationsNouveauRouteImport } from './routes/secretary/pre-consultations/nouveau'
import { Route as SecretaryPreConsultationsIdRouteImport } from './routes/secretary/pre-consultations/$id'
import { Route as SecretaryPatientsNouveauRouteImport } from './routes/secretary/patients/nouveau'
import { Route as SecretaryPatientsIdRouteImport } from './routes/secretary/patients/$id'
import { Route as PractitionerSeancePatientIdRouteImport } from './routes/practitioner/seance/$patientId'
import { Route as AdminPreConsultationsNouveauRouteImport } from './routes/admin/pre-consultations/nouveau'
import { Route as AdminPreConsultationsIdRouteImport } from './routes/admin/pre-consultations/$id'
import { Route as AdminPatientsNouveauRouteImport } from './routes/admin/patients/nouveau'
import { Route as AdminPatientsIdRouteImport } from './routes/admin/patients/$id'
import { Route as AdminConfigZonesRouteImport } from './routes/admin/config/zones'
import { Route as AdminConfigUsersRouteImport } from './routes/admin/config/users'
import { Route as AdminConfigRolesRouteImport } from './routes/admin/config/roles'
import { Route as AdminConfigQuestionnaireRouteImport } from './routes/admin/config/questionnaire'
import { Route as AdminConfigPromotionsRouteImport } from './routes/admin/config/promotions'
import { Route as AdminConfigPacksRouteImport } from './routes/admin/config/packs'
import { Route as AdminConfigBoxesRouteImport } from './routes/admin/config/boxes'

const SecretaryRoute = SecretaryRouteImport.update({
  id: '/secretary',
  path: '/secretary',
  getParentRoute: () => rootRouteImport,
} as any)
const PractitionerRoute = PractitionerRouteImport.update({
  id: '/practitioner',
  path: '/practitioner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayRoute = DisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretaryIndexRoute = SecretaryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SecretaryRoute,
} as any)
const PractitionerIndexRoute = PractitionerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PractitionerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SecretaryPaiementsRoute = SecretaryPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => SecretaryRoute,
} as any)
const SecretaryAgendaRoute = SecretaryAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => SecretaryRoute,
} as any)
const PractitionerSelectBoxRoute = PractitionerSelectBoxRouteImport.update({
  id: '/select-box',
  path: '/select-box',
  getParentRoute: () => PractitionerRoute,
} as any)
const PractitionerActiveRoute = PractitionerActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => PractitionerRoute,
} as any)
const AdminQueueRoute = AdminQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaiementsRoute = AdminPaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const SecretaryPreConsultationsIndexRoute =
  SecretaryPreConsultationsIndexRouteImport.update({
    id: '/pre-consultations/',
    path: '/pre-consultations/',
    getParentRoute: () => SecretaryRoute,
  } as any)
const SecretaryPatientsIndexRoute = SecretaryPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => SecretaryRoute,
} as any)
const AdminPreConsultationsIndexRoute =
  AdminPreConsultationsIndexRouteImport.update({
    id: '/pre-consultations/',
    path: '/pre-consultations/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPatientsIndexRoute = AdminPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AdminRoute,
} as any)
const SecretaryPreConsultationsNouveauRoute =
  SecretaryPreConsultationsNouveauRouteImport.update({
    id: '/pre-consultations/nouveau',
    path: '/pre-consultations/nouveau',
    getParentRoute: () => SecretaryRoute,
  } as any)
const SecretaryPreConsultationsIdRoute =
  SecretaryPreConsultationsIdRouteImport.update({
    id: '/pre-consultations/$id',
    path: '/pre-consultations/$id',
    getParentRoute: () => SecretaryRoute,
  } as any)
const SecretaryPatientsNouveauRoute =
  SecretaryPatientsNouveauRouteImport.update({
    id: '/patients/nouveau',
    path: '/patients/nouveau',
    getParentRoute: () => SecretaryRoute,
  } as any)
const SecretaryPatientsIdRoute = SecretaryPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => SecretaryRoute,
} as any)
const PractitionerSeancePatientIdRoute =
  PractitionerSeancePatientIdRouteImport.update({
    id: '/seance/$patientId',
    path: '/seance/$patientId',
    getParentRoute: () => PractitionerRoute,
  } as any)
const AdminPreConsultationsNouveauRoute =
  AdminPreConsultationsNouveauRouteImport.update({
    id: '/pre-consultations/nouveau',
    path: '/pre-consultations/nouveau',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminPreConsultationsIdRoute = AdminPreConsultationsIdRouteImport.update({
  id: '/pre-consultations/$id',
  path: '/pre-consultations/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsNouveauRoute = AdminPatientsNouveauRouteImport.update({
  id: '/patients/nouveau',
  path: '/patients/nouveau',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPatientsIdRoute = AdminPatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigZonesRoute = AdminConfigZonesRouteImport.update({
  id: '/config/zones',
  path: '/config/zones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigUsersRoute = AdminConfigUsersRouteImport.update({
  id: '/config/users',
  path: '/config/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigRolesRoute = AdminConfigRolesRouteImport.update({
  id: '/config/roles',
  path: '/config/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigQuestionnaireRoute =
  AdminConfigQuestionnaireRouteImport.update({
    id: '/config/questionnaire',
    path: '/config/questionnaire',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConfigPromotionsRoute = AdminConfigPromotionsRouteImport.update({
  id: '/config/promotions',
  path: '/config/promotions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigPacksRoute = AdminConfigPacksRouteImport.update({
  id: '/config/packs',
  path: '/config/packs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfigBoxesRoute = AdminConfigBoxesRouteImport.update({
  id: '/config/boxes',
  path: '/config/boxes',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/display': typeof DisplayRoute
  '/login': typeof LoginRoute
  '/practitioner': typeof PractitionerRouteWithChildren
  '/secretary': typeof SecretaryRouteWithChildren
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/practitioner/active': typeof PractitionerActiveRoute
  '/practitioner/select-box': typeof PractitionerSelectBoxRoute
  '/secretary/agenda': typeof SecretaryAgendaRoute
  '/secretary/paiements': typeof SecretaryPaiementsRoute
  '/admin/': typeof AdminIndexRoute
  '/practitioner/': typeof PractitionerIndexRoute
  '/secretary/': typeof SecretaryIndexRoute
  '/admin/config/boxes': typeof AdminConfigBoxesRoute
  '/admin/config/packs': typeof AdminConfigPacksRoute
  '/admin/config/promotions': typeof AdminConfigPromotionsRoute
  '/admin/config/questionnaire': typeof AdminConfigQuestionnaireRoute
  '/admin/config/roles': typeof AdminConfigRolesRoute
  '/admin/config/users': typeof AdminConfigUsersRoute
  '/admin/config/zones': typeof AdminConfigZonesRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/patients/nouveau': typeof AdminPatientsNouveauRoute
  '/admin/pre-consultations/$id': typeof AdminPreConsultationsIdRoute
  '/admin/pre-consultations/nouveau': typeof AdminPreConsultationsNouveauRoute
  '/practitioner/seance/$patientId': typeof PractitionerSeancePatientIdRoute
  '/secretary/patients/$id': typeof SecretaryPatientsIdRoute
  '/secretary/patients/nouveau': typeof SecretaryPatientsNouveauRoute
  '/secretary/pre-consultations/$id': typeof SecretaryPreConsultationsIdRoute
  '/secretary/pre-consultations/nouveau': typeof SecretaryPreConsultationsNouveauRoute
  '/admin/patients/': typeof AdminPatientsIndexRoute
  '/admin/pre-consultations/': typeof AdminPreConsultationsIndexRoute
  '/secretary/patients/': typeof SecretaryPatientsIndexRoute
  '/secretary/pre-consultations/': typeof SecretaryPreConsultationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/display': typeof DisplayRoute
  '/login': typeof LoginRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/practitioner/active': typeof PractitionerActiveRoute
  '/practitioner/select-box': typeof PractitionerSelectBoxRoute
  '/secretary/agenda': typeof SecretaryAgendaRoute
  '/secretary/paiements': typeof SecretaryPaiementsRoute
  '/admin': typeof AdminIndexRoute
  '/practitioner': typeof PractitionerIndexRoute
  '/secretary': typeof SecretaryIndexRoute
  '/admin/config/boxes': typeof AdminConfigBoxesRoute
  '/admin/config/packs': typeof AdminConfigPacksRoute
  '/admin/config/promotions': typeof AdminConfigPromotionsRoute
  '/admin/config/questionnaire': typeof AdminConfigQuestionnaireRoute
  '/admin/config/roles': typeof AdminConfigRolesRoute
  '/admin/config/users': typeof AdminConfigUsersRoute
  '/admin/config/zones': typeof AdminConfigZonesRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/patients/nouveau': typeof AdminPatientsNouveauRoute
  '/admin/pre-consultations/$id': typeof AdminPreConsultationsIdRoute
  '/admin/pre-consultations/nouveau': typeof AdminPreConsultationsNouveauRoute
  '/practitioner/seance/$patientId': typeof PractitionerSeancePatientIdRoute
  '/secretary/patients/$id': typeof SecretaryPatientsIdRoute
  '/secretary/patients/nouveau': typeof SecretaryPatientsNouveauRoute
  '/secretary/pre-consultations/$id': typeof SecretaryPreConsultationsIdRoute
  '/secretary/pre-consultations/nouveau': typeof SecretaryPreConsultationsNouveauRoute
  '/admin/patients': typeof AdminPatientsIndexRoute
  '/admin/pre-consultations': typeof AdminPreConsultationsIndexRoute
  '/secretary/patients': typeof SecretaryPatientsIndexRoute
  '/secretary/pre-consultations': typeof SecretaryPreConsultationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/display': typeof DisplayRoute
  '/login': typeof LoginRoute
  '/practitioner': typeof PractitionerRouteWithChildren
  '/secretary': typeof SecretaryRouteWithChildren
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/paiements': typeof AdminPaiementsRoute
  '/admin/queue': typeof AdminQueueRoute
  '/practitioner/active': typeof PractitionerActiveRoute
  '/practitioner/select-box': typeof PractitionerSelectBoxRoute
  '/secretary/agenda': typeof SecretaryAgendaRoute
  '/secretary/paiements': typeof SecretaryPaiementsRoute
  '/admin/': typeof AdminIndexRoute
  '/practitioner/': typeof PractitionerIndexRoute
  '/secretary/': typeof SecretaryIndexRoute
  '/admin/config/boxes': typeof AdminConfigBoxesRoute
  '/admin/config/packs': typeof AdminConfigPacksRoute
  '/admin/config/promotions': typeof AdminConfigPromotionsRoute
  '/admin/config/questionnaire': typeof AdminConfigQuestionnaireRoute
  '/admin/config/roles': typeof AdminConfigRolesRoute
  '/admin/config/users': typeof AdminConfigUsersRoute
  '/admin/config/zones': typeof AdminConfigZonesRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/patients/nouveau': typeof AdminPatientsNouveauRoute
  '/admin/pre-consultations/$id': typeof AdminPreConsultationsIdRoute
  '/admin/pre-consultations/nouveau': typeof AdminPreConsultationsNouveauRoute
  '/practitioner/seance/$patientId': typeof PractitionerSeancePatientIdRoute
  '/secretary/patients/$id': typeof SecretaryPatientsIdRoute
  '/secretary/patients/nouveau': typeof SecretaryPatientsNouveauRoute
  '/secretary/pre-consultations/$id': typeof SecretaryPreConsultationsIdRoute
  '/secretary/pre-consultations/nouveau': typeof SecretaryPreConsultationsNouveauRoute
  '/admin/patients/': typeof AdminPatientsIndexRoute
  '/admin/pre-consultations/': typeof AdminPreConsultationsIndexRoute
  '/secretary/patients/': typeof SecretaryPatientsIndexRoute
  '/secretary/pre-consultations/': typeof SecretaryPreConsultationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/display'
    | '/login'
    | '/practitioner'
    | '/secretary'
    | '/admin/agenda'
    | '/admin/paiements'
    | '/admin/queue'
    | '/practitioner/active'
    | '/practitioner/select-box'
    | '/secretary/agenda'
    | '/secretary/paiements'
    | '/admin/'
    | '/practitioner/'
    | '/secretary/'
    | '/admin/config/boxes'
    | '/admin/config/packs'
    | '/admin/config/promotions'
    | '/admin/config/questionnaire'
    | '/admin/config/roles'
    | '/admin/config/users'
    | '/admin/config/zones'
    | '/admin/patients/$id'
    | '/admin/patients/nouveau'
    | '/admin/pre-consultations/$id'
    | '/admin/pre-consultations/nouveau'
    | '/practitioner/seance/$patientId'
    | '/secretary/patients/$id'
    | '/secretary/patients/nouveau'
    | '/secretary/pre-consultations/$id'
    | '/secretary/pre-consultations/nouveau'
    | '/admin/patients/'
    | '/admin/pre-consultations/'
    | '/secretary/patients/'
    | '/secretary/pre-consultations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/display'
    | '/login'
    | '/admin/agenda'
    | '/admin/paiements'
    | '/admin/queue'
    | '/practitioner/active'
    | '/practitioner/select-box'
    | '/secretary/agenda'
    | '/secretary/paiements'
    | '/admin'
    | '/practitioner'
    | '/secretary'
    | '/admin/config/boxes'
    | '/admin/config/packs'
    | '/admin/config/promotions'
    | '/admin/config/questionnaire'
    | '/admin/config/roles'
    | '/admin/config/users'
    | '/admin/config/zones'
    | '/admin/patients/$id'
    | '/admin/patients/nouveau'
    | '/admin/pre-consultations/$id'
    | '/admin/pre-consultations/nouveau'
    | '/practitioner/seance/$patientId'
    | '/secretary/patients/$id'
    | '/secretary/patients/nouveau'
    | '/secretary/pre-consultations/$id'
    | '/secretary/pre-consultations/nouveau'
    | '/admin/patients'
    | '/admin/pre-consultations'
    | '/secretary/patients'
    | '/secretary/pre-consultations'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/display'
    | '/login'
    | '/practitioner'
    | '/secretary'
    | '/admin/agenda'
    | '/admin/paiements'
    | '/admin/queue'
    | '/practitioner/active'
    | '/practitioner/select-box'
    | '/secretary/agenda'
    | '/secretary/paiements'
    | '/admin/'
    | '/practitioner/'
    | '/secretary/'
    | '/admin/config/boxes'
    | '/admin/config/packs'
    | '/admin/config/promotions'
    | '/admin/config/questionnaire'
    | '/admin/config/roles'
    | '/admin/config/users'
    | '/admin/config/zones'
    | '/admin/patients/$id'
    | '/admin/patients/nouveau'
    | '/admin/pre-consultations/$id'
    | '/admin/pre-consultations/nouveau'
    | '/practitioner/seance/$patientId'
    | '/secretary/patients/$id'
    | '/secretary/patients/nouveau'
    | '/secretary/pre-consultations/$id'
    | '/secretary/pre-consultations/nouveau'
    | '/admin/patients/'
    | '/admin/pre-consultations/'
    | '/secretary/patients/'
    | '/secretary/pre-consultations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DisplayRoute: typeof DisplayRoute
  LoginRoute: typeof LoginRoute
  PractitionerRoute: typeof PractitionerRouteWithChildren
  SecretaryRoute: typeof SecretaryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/secretary': {
      id: '/secretary'
      path: '/secretary'
      fullPath: '/secretary'
      preLoaderRoute: typeof SecretaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practitioner': {
      id: '/practitioner'
      path: '/practitioner'
      fullPath: '/practitioner'
      preLoaderRoute: typeof PractitionerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display': {
      id: '/display'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretary/': {
      id: '/secretary/'
      path: '/'
      fullPath: '/secretary/'
      preLoaderRoute: typeof SecretaryIndexRouteImport
      parentRoute: typeof SecretaryRoute
    }
    '/practitioner/': {
      id: '/practitioner/'
      path: '/'
      fullPath: '/practitioner/'
      preLoaderRoute: typeof PractitionerIndexRouteImport
      parentRoute: typeof PractitionerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/secretary/paiements': {
      id: '/secretary/paiements'
      path: '/paiements'
      fullPath: '/secretary/paiements'
      preLoaderRoute: typeof SecretaryPaiementsRouteImport
      parentRoute: typeof SecretaryRoute
    }
    '/secretary/agenda': {
      id: '/secretary/agenda'
      path: '/agenda'
      fullPath: '/secretary/agenda'
      preLoaderRoute: typeof SecretaryAgendaRouteImport
      parentRoute: typeof SecretaryRoute
    }
    '/practitioner/select-box': {
      id: '/practitioner/select-box'
      path: '/select-box'
      fullPath: '/practitioner/select-box'
      preLoaderRoute: typeof PractitionerSelectBoxRouteImport
      parentRoute: typeof PractitionerRoute
    }
    '/practitioner/active': {
      id: '/practitioner/active'
      path: '/active'
      fullPath: '/practitioner/active'
      preLoaderRoute: typeof PractitionerActiveRouteImport
      parentRoute: typeof PractitionerRoute
    }
    '/admin/queue': {
      id: '/admin/queue'
      path: '/queue'
      fullPath: '/admin/queue'
      preLoaderRoute: typeof AdminQueueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/paiements': {
      id: '/admin/paiements'
      path: '/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AdminPaiementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/secretary/pre-consultations/': {
      id: '/secretary/pre-consultations/'
      path: '/pre-consultations'
      fullPath: '/secretary/pre-consultations/'
      preLoaderRoute: typeof SecretaryPreConsultationsIndexRouteImport
      parentRoute: typeof SecretaryRoute
    }
    '/secretary/patients/': {
      id: '/secretary/patients/'
      path: '/patients'
      fullPath: '/secretary/patients/'
      preLoaderRoute: typeof SecretaryPatientsIndexRouteImport
      parentRoute: typeof SecretaryRoute
    }
    '/admin/pre-consultations/': {
      id: '/admin/pre-consultations/'
      path: '/pre-consultations'
      fullPath: '/admin/pre-consultations/'
      preLoaderRoute: typeof AdminPreConsultationsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients/': {
      id: '/admin/patients/'
      path: '/patients'
      fullPath: '/admin/patients/'
      preLoaderRoute: typeof AdminPatientsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/secretary/pre-consultations/nouveau': {
      id: '/secretary/pre-consultations/nouveau'
      path: '/pre-consultations/nouveau'
      fullPath: '/secretary/pre-consultations/nouveau'
      preLoaderRoute: typeof SecretaryPreConsultationsNouveauRouteImport
      parentRoute: typeof SecretaryRoute
    }
    '/secretary/pre-consultations/$id': {
      id: '/secretary/pre-consultations/$id'
      path: '/pre-consultations/$id'
      fullPath: '/secretary/pre-consultations/$id'
      preLoaderRoute: typeof SecretaryPreConsultationsIdRouteImport
      parentRoute: typeof SecretaryRoute
    }
    '/secretary/patients/nouveau': {
      id: '/secretary/patients/nouveau'
      path: '/patients/nouveau'
      fullPath: '/secretary/patients/nouveau'
      preLoaderRoute: typeof SecretaryPatientsNouveauRouteImport
      parentRoute: typeof SecretaryRoute
    }
    '/secretary/patients/$id': {
      id: '/secretary/patients/$id'
      path: '/patients/$id'
      fullPath: '/secretary/patients/$id'
      preLoaderRoute: typeof SecretaryPatientsIdRouteImport
      parentRoute: typeof SecretaryRoute
    }
    '/practitioner/seance/$patientId': {
      id: '/practitioner/seance/$patientId'
      path: '/seance/$patientId'
      fullPath: '/practitioner/seance/$patientId'
      preLoaderRoute: typeof PractitionerSeancePatientIdRouteImport
      parentRoute: typeof PractitionerRoute
    }
    '/admin/pre-consultations/nouveau': {
      id: '/admin/pre-consultations/nouveau'
      path: '/pre-consultations/nouveau'
      fullPath: '/admin/pre-consultations/nouveau'
      preLoaderRoute: typeof AdminPreConsultationsNouveauRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pre-consultations/$id': {
      id: '/admin/pre-consultations/$id'
      path: '/pre-consultations/$id'
      fullPath: '/admin/pre-consultations/$id'
      preLoaderRoute: typeof AdminPreConsultationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients/nouveau': {
      id: '/admin/patients/nouveau'
      path: '/patients/nouveau'
      fullPath: '/admin/patients/nouveau'
      preLoaderRoute: typeof AdminPatientsNouveauRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/patients/$id': {
      id: '/admin/patients/$id'
      path: '/patients/$id'
      fullPath: '/admin/patients/$id'
      preLoaderRoute: typeof AdminPatientsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config/zones': {
      id: '/admin/config/zones'
      path: '/config/zones'
      fullPath: '/admin/config/zones'
      preLoaderRoute: typeof AdminConfigZonesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config/users': {
      id: '/admin/config/users'
      path: '/config/users'
      fullPath: '/admin/config/users'
      preLoaderRoute: typeof AdminConfigUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config/roles': {
      id: '/admin/config/roles'
      path: '/config/roles'
      fullPath: '/admin/config/roles'
      preLoaderRoute: typeof AdminConfigRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config/questionnaire': {
      id: '/admin/config/questionnaire'
      path: '/config/questionnaire'
      fullPath: '/admin/config/questionnaire'
      preLoaderRoute: typeof AdminConfigQuestionnaireRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config/promotions': {
      id: '/admin/config/promotions'
      path: '/config/promotions'
      fullPath: '/admin/config/promotions'
      preLoaderRoute: typeof AdminConfigPromotionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config/packs': {
      id: '/admin/config/packs'
      path: '/config/packs'
      fullPath: '/admin/config/packs'
      preLoaderRoute: typeof AdminConfigPacksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/config/boxes': {
      id: '/admin/config/boxes'
      path: '/config/boxes'
      fullPath: '/admin/config/boxes'
      preLoaderRoute: typeof AdminConfigBoxesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminPaiementsRoute: typeof AdminPaiementsRoute
  AdminQueueRoute: typeof AdminQueueRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConfigBoxesRoute: typeof AdminConfigBoxesRoute
  AdminConfigPacksRoute: typeof AdminConfigPacksRoute
  AdminConfigPromotionsRoute: typeof AdminConfigPromotionsRoute
  AdminConfigQuestionnaireRoute: typeof AdminConfigQuestionnaireRoute
  AdminConfigRolesRoute: typeof AdminConfigRolesRoute
  AdminConfigUsersRoute: typeof AdminConfigUsersRoute
  AdminConfigZonesRoute: typeof AdminConfigZonesRoute
  AdminPatientsIdRoute: typeof AdminPatientsIdRoute
  AdminPatientsNouveauRoute: typeof AdminPatientsNouveauRoute
  AdminPreConsultationsIdRoute: typeof AdminPreConsultationsIdRoute
  AdminPreConsultationsNouveauRoute: typeof AdminPreConsultationsNouveauRoute
  AdminPatientsIndexRoute: typeof AdminPatientsIndexRoute
  AdminPreConsultationsIndexRoute: typeof AdminPreConsultationsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminPaiementsRoute: AdminPaiementsRoute,
  AdminQueueRoute: AdminQueueRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminConfigBoxesRoute: AdminConfigBoxesRoute,
  AdminConfigPacksRoute: AdminConfigPacksRoute,
  AdminConfigPromotionsRoute: AdminConfigPromotionsRoute,
  AdminConfigQuestionnaireRoute: AdminConfigQuestionnaireRoute,
  AdminConfigRolesRoute: AdminConfigRolesRoute,
  AdminConfigUsersRoute: AdminConfigUsersRoute,
  AdminConfigZonesRoute: AdminConfigZonesRoute,
  AdminPatientsIdRoute: AdminPatientsIdRoute,
  AdminPatientsNouveauRoute: AdminPatientsNouveauRoute,
  AdminPreConsultationsIdRoute: AdminPreConsultationsIdRoute,
  AdminPreConsultationsNouveauRoute: AdminPreConsultationsNouveauRoute,
  AdminPatientsIndexRoute: AdminPatientsIndexRoute,
  AdminPreConsultationsIndexRoute: AdminPreConsultationsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PractitionerRouteChildren {
  PractitionerActiveRoute: typeof PractitionerActiveRoute
  PractitionerSelectBoxRoute: typeof PractitionerSelectBoxRoute
  PractitionerIndexRoute: typeof PractitionerIndexRoute
  PractitionerSeancePatientIdRoute: typeof PractitionerSeancePatientIdRoute
}

const PractitionerRouteChildren: PractitionerRouteChildren = {
  PractitionerActiveRoute: PractitionerActiveRoute,
  PractitionerSelectBoxRoute: PractitionerSelectBoxRoute,
  PractitionerIndexRoute: PractitionerIndexRoute,
  PractitionerSeancePatientIdRoute: PractitionerSeancePatientIdRoute,
}

const PractitionerRouteWithChildren = PractitionerRoute._addFileChildren(
  PractitionerRouteChildren,
)

interface SecretaryRouteChildren {
  SecretaryAgendaRoute: typeof SecretaryAgendaRoute
  SecretaryPaiementsRoute: typeof SecretaryPaiementsRoute
  SecretaryIndexRoute: typeof SecretaryIndexRoute
  SecretaryPatientsIdRoute: typeof SecretaryPatientsIdRoute
  SecretaryPatientsNouveauRoute: typeof SecretaryPatientsNouveauRoute
  SecretaryPreConsultationsIdRoute: typeof SecretaryPreConsultationsIdRoute
  SecretaryPreConsultationsNouveauRoute: typeof SecretaryPreConsultationsNouveauRoute
  SecretaryPatientsIndexRoute: typeof SecretaryPatientsIndexRoute
  SecretaryPreConsultationsIndexRoute: typeof SecretaryPreConsultationsIndexRoute
}

const SecretaryRouteChildren: SecretaryRouteChildren = {
  SecretaryAgendaRoute: SecretaryAgendaRoute,
  SecretaryPaiementsRoute: SecretaryPaiementsRoute,
  SecretaryIndexRoute: SecretaryIndexRoute,
  SecretaryPatientsIdRoute: SecretaryPatientsIdRoute,
  SecretaryPatientsNouveauRoute: SecretaryPatientsNouveauRoute,
  SecretaryPreConsultationsIdRoute: SecretaryPreConsultationsIdRoute,
  SecretaryPreConsultationsNouveauRoute: SecretaryPreConsultationsNouveauRoute,
  SecretaryPatientsIndexRoute: SecretaryPatientsIndexRoute,
  SecretaryPreConsultationsIndexRoute: SecretaryPreConsultationsIndexRoute,
}

const SecretaryRouteWithChildren = SecretaryRoute._addFileChildren(
  SecretaryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DisplayRoute: DisplayRoute,
  LoginRoute: LoginRoute,
  PractitionerRoute: PractitionerRouteWithChildren,
  SecretaryRoute: SecretaryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
